# Generated by Django 2.1.4 on 2018-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OldName', models.CharField(max_length=255)),
                ('NewName', models.CharField(max_length=255)),
                ('LocationNumber', models.IntegerField(default=0)),
                ('DrawingNumber', models.IntegerField(default=0)),
                ('ProjectTitle', models.CharField(max_length=255)),
                ('ProjectNumber', models.CharField(max_length=255)),
                ('DrawingDate', models.IntegerField(default=0)),
                ('SheetTitle', models.CharField(max_length=255)),
                ('SheetNumber', models.CharField(max_length=255)),
                ('Discipline', models.CharField(max_length=255)),
                ('DrawingVersion', models.CharField(max_length=255)),
                ('Notes', models.CharField(max_length=255)),
                ('PhysicalLocation', models.CharField(max_length=255)),
            ],
        ),
    ]
